version: "3.9"
services:
  web:
    platform: linux/x86_64
    build:
      context: .
      target: dev
    stdin_open: true
    tty: true
    command: bundle exec puma --port 3000
    volumes:
      - ".:/app"
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    platform: linux/x86_64
    image: "redis:6-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
volumes:
  bundle:
  redis:
